Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLNS1.Data;
using QLNS1.Models;

namespace QLNS1.Controllers
{
    [Authorize(Roles = "Admin,Manager")]
    public class BooksController : Controller
    {
        private readonly QLNS1Context _context;
        public BooksController(QLNS1Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return _context.Sach != null ?
                        View(await _context.Sach.ToListAsync()) :
                        Problem("Entity set 'QLNS1Context.Sach'  is null.");
        }
        
        [AllowAnonymous]
        public async Task<IActionResult> Display()
        {
            var book = await _context.Sach.ToListAsync();

            if (book == null || book.Count == 0)
                return NotFound();

            return View(book);
        }

        [AllowAnonymous]
        public IActionResult LookUp(string searchString)
        {
            var books = string.IsNullOrWhiteSpace(searchString)
                            ? _context.Sach.ToList()
                            : _context.Sach.Where(s => s.Name.Contains(searchString) || s.Author.Contains(searchString)).ToList();

            return View(books);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id,Name,Author,Type,Amount,Price,Picture")] Sach book)
        {
            _context.Add(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Sach == null)
                return NotFound();

            var book = await _context.Sach
                .FirstOrDefaultAsync(m => m.SachId == id);
            if (book == null)
                return NotFound();

            return View(book);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Sach == null)
                return NotFound();

            var book = await _context.Sach.FindAsync(id);
            if (book == null)
                return NotFound();

            return View(book);
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SachId,Name,Author,Type,Amount,Price,Picture")] Sach book)
        {
            book.SachId = id;
            if (!ModelState.IsValid)
                return View(book);
            try
            {
                _context.Update(book);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SachExists(book.SachId))
                    return NotFound();
                else
                    throw;
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Sach == null)
                return NotFound();

            var book = await _context.Sach
                .FirstOrDefaultAsync(m => m.SachId == id);
            if (book == null)
                return NotFound();

            return View(book);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Sach == null)
                return Problem("Entity set 'QLNS1Context.Sach'  is null.");
            var book = await _context.Sach.FindAsync(id);
            if (book != null)
                _context.Sach.Remove(book);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Inventory()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Inventory(IFormCollection form)
        {
            var selectedMonth = form["Thang"];
            var sachList = _context.Sach.ToList();
            var viewModelList = new List<HienHoaDon>();

            foreach (var sach in sachList)
            {
                var nhapSach = _context.Nhap.FirstOrDefault(s => s.TenSach == sach.Name);

                if (nhapSach != null)
                {
                    var tonCuoiNam = sach.Amount;
                    var phatSinh = _context.Nhap
                        .Where(o => o.DateImport.Month == Int32.Parse(selectedMonth) && o.TenSach == sach.Name)
                        .Sum(o => o.AmountImport);
                    var tonDauNam = TinhTonDauThang(sach.Name, selectedMonth);

                    var viewModel = new HienHoaDon
                    {
                        TenSach = sach.Name,
                        TonCuoiNam = tonCuoiNam,
                        PhatSinh = phatSinh,
                        TonDauNam = tonDauNam
                    };

                    viewModelList.Add(viewModel);
                }
            }

            return View("List", viewModelList);
        }

        private bool SachExists(int id)
        {
            return (_context.Sach?.Any(e => e.SachId == id)).GetValueOrDefault();
        }
        
        private int TinhTonDauThang(string tenSach, string thang)
        {
            var nhapSachTheoThang = _context.Nhap
                .Where(s => s.TenSach == tenSach && s.DateImport.Month == Int32.Parse(thang))
                .ToList();

            var nhapSachCuoiCungTheoThang = nhapSachTheoThang
                .OrderByDescending(o => o.DateImport.Day)
                .FirstOrDefault();

            var hoaDonThang = _context.Nhap
                .Where(o => o.DateImport.Month == Int32.Parse(thang))
                .ToList();

            var hoaDonTuNgayNhapCuoiCung = hoaDonThang
                .Where(o => o.DateImport.Day >= nhapSachCuoiCungTheoThang.DateImport.Day)
                .ToList();

            var tongSoLuongBan = hoaDonTuNgayNhapCuoiCung.Sum(o => o.AmountImport);
            var tonDauThang = nhapSachCuoiCungTheoThang.SachSauNhap - tongSoLuongBan;

            return tonDauThang;
        }

    }
}

Controllers/CollectPaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLNS1.Data;
using QLNS1.Models;

namespace QLNS1.Controllers
{
    public class CollectPaymentController : Controller
    {
        private readonly QLNS1Context _context;
        public CollectPaymentController(QLNS1Context context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
              return _context.ThuTien != null ? 
                          View(await _context.ThuTien.ToListAsync()) :
                          Problem("Entity set 'QLNS1Context.ThuTien'  is null.");
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("IdThuTien,HoTen,DiaChi,SoDienThoai,Email,NgayThu,SoTienThu")] ThuTien thuTien)
        {
            if (ModelState.IsValid)
            {
                var user = _context.Users.FirstOrDefault(u => u.Email == thuTien.Email || u.PhoneNumber == thuTien.SoDienThoai);
                if (user != null)
                {
                    if (user.TienNo >= thuTien.SoTienThu)
                    {
                        user.TienNo = user.TienNo - thuTien.SoTienThu;
                        thuTien.NgayThu = DateTime.Now;
                        _context.Add(thuTien);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError("SoTienThu", "Số tiền thu vượt quá tiền nợ");
                    }
                }
            }
            return View(thuTien);
        }
        private bool ThuTienExists(int id)
        {
          return (_context.ThuTien?.Any(e => e.IdThuTien == id)).GetValueOrDefault();
        }
    }
}

Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLNS1.Data;
using QLNS1.Models;

namespace QLNS1.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly QLNS1Context _context;

        public InvoicesController(QLNS1Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return _context.Invoice != null ?
                        View(await _context.Invoice.ToListAsync()) :
                        Problem("Entity set 'QLNS1Context.Invoice'  is null.");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("MaHoaDon,TenKhachHang,TenSach,TheLoai,SoLuong,Gia,Date,sdt,Debt")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                var book = _context.Sach.FirstOrDefault(s => s.Name == invoice.TenSach && s.Type == invoice.TheLoai);
                if (book != null)
                {
                    var remainingQuantity = book.Amount;
                    if (remainingQuantity - invoice.SoLuong >= 10)
                    {
                        invoice.Gia = book.Price * invoice.SoLuong;
                        invoice.Date = DateTime.Now;
                        book.Amount -= invoice.SoLuong;
                        if (invoice.Debt == 1)
                        {
                            //TODO: update user debt
                            var user = _context.Users.FirstOrDefault(u => u.PhoneNumber == invoice.sdt);
                            user.TienNo += invoice.Gia;
                            user.NgayNo = DateTime.Now.ToString();
                            _context.Update(user);
                        }
                        _context.Add(invoice);
                        _context.Update(book);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ModelState.AddModelError("SoLuong", "Số lượng sách không đủ");
                        return View(invoice);
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Invoice == null)
                return NotFound();

            var invoice = await _context.Invoice
                .FirstOrDefaultAsync(m => m.MaHoaDon == id);
            if (invoice == null)
                return NotFound();

            return View(invoice);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Invoice == null)
                return NotFound();

            var invoice = await _context.Invoice
                .FirstOrDefaultAsync(m => m.MaHoaDon == id);
            if (invoice == null)
                return NotFound();

            return View(invoice);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaHoaDon,TenKhachHang,TenSach,TheLoai,SoLuong,Gia,Date,sdt,Debt")] Invoice invoice)
        {
            invoice.MaHoaDon = id;
            if (ModelState.IsValid)
            {
                try
                {
                    var sach = _context.Sach.FirstOrDefault(s => s.Name == invoice.TenSach && s.Type == invoice.TheLoai);
                    if (sach != null)
                    {
                        var originalInvoice = await _context.Invoice.AsNoTracking().FirstOrDefaultAsync(i => i.MaHoaDon == id);
                        var quantityDifference = originalInvoice.SoLuong - invoice.SoLuong;

                        if (sach.Amount + quantityDifference >= 0)
                        {
                            invoice.Gia = sach.Price * invoice.SoLuong;
                            invoice.Date = DateTime.Now;
                            sach.Amount += quantityDifference;

                            if (originalInvoice.Debt == 1 && invoice.Debt == 0)
                            {
                                // TODO: deduct debt from user
                                var user = _context.Users.FirstOrDefault(u => u.PhoneNumber == invoice.sdt);
                                user.TienNo -= originalInvoice.Gia;
                                _context.Update(user);
                            }
                            else if (originalInvoice.Debt == 0 && invoice.Debt == 1)
                            {
                                // TODO: add debt to user
                                var user = _context.Users.FirstOrDefault(u => u.PhoneNumber == invoice.sdt);
                                user.TienNo += invoice.Gia;
                                user.NgayNo = DateTime.Now.ToString();
                                _context.Update(user);
                            }

                            _context.Update(invoice);
                            _context.Update(sach);
                            await _context.SaveChangesAsync();
                        }
                        else
                        {
                            ModelState.AddModelError("SoLuong", "Số lượng sách không đủ");
                            return View(invoice);
                        }
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InvoiceExists(invoice.MaHoaDon))
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(invoice);
        }

        private bool InvoiceExists(int id)
        {
            return (_context.Invoice?.Any(e => e.MaHoaDon == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Invoice == null)
                return NotFound();

            var invoice = await _context.Invoice
                .FirstOrDefaultAsync(m => m.MaHoaDon == id);
            if (invoice == null)
                return NotFound();

            return View(invoice);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Invoice == null)
                return Problem("Entity set 'QLNS1Context.Invoice' is null.");
            var invoice = await _context.Invoice.FindAsync(id);
            if (invoice != null)
                _context.Invoice.Remove(invoice);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult DebtReport()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> DebtReport(IFormCollection form)
        {
            var selectedMonth = form["Thang"];
            var users = _context.Users.ToList();
            var viewModelList = new List<HienTienNo>();
            foreach (var user in users)
            {
                var hoaDon = _context.Invoice.FirstOrDefault(s => s.sdt == user.PhoneNumber);

                if (hoaDon != null)
                {
                    var tonCuoiThang = user.TienNo;
                    var phatSinh = _context.Invoice
                        .Where(o => o.Date.Month == Int32.Parse(selectedMonth) && o.sdt == user.PhoneNumber && o.Debt == 1)
                        .Sum(o => o.Gia);
                    var tonDauThang = TinhTonDauThang(user.PhoneNumber, selectedMonth);

                    var viewModel = new HienTienNo
                    {
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        PhoneNumber = user.PhoneNumber,
                        NoCuoiThang = tonCuoiThang,
                        PhatSinh = phatSinh,
                        NoDauThang = tonDauThang
                    };                    
                    viewModelList.Add(viewModel);
                }
            }
            return View("List", viewModelList);

        }
        private int TinhTonDauThang(string sdt, string month)
        {
            var invoices = _context.Invoice.Where(s => s.sdt == sdt && s.Date.Month == Int32.Parse(month)).ToList();
            return invoices.Sum(o => o.Gia);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<style>
    .search-containerr {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 5vh;
    }

    .form-controll {
        width: 950px !important;
        height: 90%;
        margin-right: 5px;
    }

    .b {
        height: 102%;
    }
</style>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QLNS1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QLNS1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img id="Book-logo" src="/images/book-icon.jpg" alt="Book Logo" draggable="false" height="50" />
                </a>
                <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <form class="d-flex align-items-center w-100 form-search" method="get" action="@Url.Action("LookUp", "Books")">
                        <div class="search-containerr">
                            <input type="search" name="searchString" class="form-controll" placeholder="Search" aria-label="Search" />
                            <button type="submit" class="btn btn-secondary b ">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                                </svg>
                            </button>
                        </div>
                    </form>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="fixed-bottom">
            &copy; 2023 - QuanLyNhaSach - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Manager.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QLNS1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/QLNS1.styles.css" asp-append-version="true" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

</head>
<body>
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-success min-vh-100 align-items-center align-items-sm-start ">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline"><b>Menu</b></span>
                </a>

                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li><a class="btn btn-outline-0 border-top border-bottom pb-3 pt-3 text-white" asp-controller="Books" asp-action="Create">Thêm sách mới</a></li>
                    <li><a class="btn btn-outline-0 border-top border-bottom pb-3 pt-3 text-white" asp-controller="Books" asp-action="Index">Xem/Xóa/Sửa sách</a></li>
                    <li><a class="btn btn-outline-0 border-top border-bottom pb-3 pt-3 text-white" asp-controller="ImportBooks" asp-action="Create">Nhập sách</a></li>
                    <li><a class="btn btn-outline-0 border-top border-bottom pb-3 pt-3 text-white" asp-controller="Books" asp-action="Display">Danh sách sách</a></li>
                    <li><a class="btn btn-outline-0 border-top border-bottom pb-3 pt-3 text-white" asp-controller="Invoices" asp-action="Create">Hóa đơn</a></li>
                    <li><a class="btn btn-outline-0 border-top border-bottom pb-3 pt-3 text-white" asp-controller="CollectPayment" asp-action="Create">Phiếu thu</a></li>
                    <li><a class="btn btn-outline-0 border-top border-bottom pb-3 pt-3 text-white" asp-controller="Books" asp-action="Inventory">Báo cáo tồn kho</a></li>
                    <li><a class="btn btn-outline-0 border-top border-bottom pb-3 pt-3 text-white" asp-controller="Invoices" asp-action="DebtReport">Báo cáo công nợ</a></li>
                </ul>
                <hr>
                <div class="pt-5">
                    <partial name="_LoginPartial" />
                </div>
            </div>
            <div class="col py-3">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>